---
- name: Web
  hosts: webserver
  become: yes
  vars_files:
    - roles/apache.yaml

  roles:
    - role: apache

- name: database 
  hosts: database 
  become: true
  vars_files:
    - roles/mysql.yaml

  roles:
    - role: mysql
