- name: install apache2 
  remote_user: mouchel 
  hosts: webserver 
  become: true 
  become_user: root 
  gather_facts: true 
  tasks: 
    - name: "Install apache2" 
      package: 
        name=apache2 
        state=present