---
- name: Web
  hosts: web
  become: yes
  vars_files:
    - roles/apache.yaml

  roles:
    - role: apache

- name: DATABASE SERVER
  hosts: db
  become: true
  vars_files:
    - roles/mysql.yaml

  roles:
    - role: mysql
